### ISSUE TITLE
Feature request : left-click a tiddler to make it active

### ISSUE THREAD

**Issue by Telumire** [MaxGyver83/tw5-keyboard-navigation#4]
Hello ! 

I love your plugin, I find it very useful. I have a suggestion : it would be great if the active tiddler could be changed by a click inside a tiddler. This way we could quickly open and edit any tiddler by left-clicking it then pressing e.

Thanks for taking the time to read this message, I wish you a great day :)

**Comment by MaxGyver83** [comment]
Hello,

thanks! This sounds like a useful feature. I'm going to implement this soon!

**Comment by MaxGyver83** [comment]
Well, it took quite a while but eventually the new version is ready!

Check the [demo page](https://maximilian-schillinger.de/tw5-keyboard-navigation-plugin.html) for **version 0.7.0**.

[Changes](https://github.com/MaxGyver83/tw5-keyboard-navigation/commit/834bfe01ebce3d48c764e1a9322171d044c746f5) besides the feature you requested:

* bug fix: highlight the correct tiddler after editing
* new: close search result popup window with `Esc`
* new: close more tiddler actions menu with `Esc`

**Comment by Telumire** [comment]
Awesome, thank you so much ! This works great 😄

**Comment by arunnbabu81** [comment]
@MaxGyver83  Can you please make this feature as separate plug-in ? It is such a useful feature. But I cant use the keyboard-navigation plug-in as whole because I am using multicolumn layout which has its own navigation mechansim. Also there has been some interest in the community regarding focus tiddler.
https://talk.tiddlywiki.org/t/how-to-create-the-functionality-focus-select-tiddler-on-mouse-hover/8112
https://talk.tiddlywiki.org/t/an-invention-you-may-be-interested-in-focused-tiddler-types-and-setting-current-focus/6076

**Comment by MaxGyver83** [comment]
@arunnbabu81 : Thanks for your interest! In general, I don't want to create (and maintain) a plugin that I don't use.

You could try this: Install this plugin, edit `keyboard-navigation.js` (Control Panel → Plugins → tw5-keyboard-navigation → contents → keyboard-navigation.js) and delete `document.onkeydown = function(e) {...}` and `document.onkeyup = function(e) {...}` (not tested).

But I think about making this plugin more configurable. Then you could disable all key input actions.

I hope that TiddlyWiki will integrate the concept of active/focused tiddlers and keyboard navigation and my plugin will be superfluous then.
